### ISSUE TITLE
[Task]: Add Linters and Testers to Pre Commit

### ISSUE THREAD

**Issue by acouch** [HHS/grants-equity#429] opened 2023-08-29 11:30 UTC
### Summary

[Pre-commit](https://github.com/HHS/grants-equity/blob/main/.pre-commit-config.yaml) has been added to the project. The api, frontend, and infra components have since been added to the project. Each of these has a linter ([infra's](https://github.com/navapbc/template-infra/blob/main/Makefile#L129) can be re-introduced) and tests that can be added to pre-commit so that tests and lints for specific file types can be run before committing.

This will save time, for both committers and code reviewers, as changes won't be introduced before linters and tests have been run and is widely adopted as a best practice.

### Acceptance criteria

- [ ] linters and tests have been added to pre-commit
- [ ] documentation is updated

**Comment by daphnegold** [comment] 2023-09-18 21:48
Duplicate of #223

**Closed by daphnegold** 2023-09-18 21:48 UTC
Labels: project: grants.gov
